In [32]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
import numpy as np

In [2]:
data=pd.read_csv("marketing_customer_analysis.csv")
data

,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,Income,...,Months Since Policy Inception,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size
0,BU79786,Washington,2763.519279,No,Basic,Bachelor,2/24/11,Employed,F,56274,...,5,0,1,Corporate Auto,Corporate L3,Offer1,Agent,384.811147,Two-Door Car,Medsize
1,QZ44356,Arizona,6979.535903,No,Extended,Bachelor,1/31/11,Unemployed,F,0,...,42,0,8,Personal Auto,Personal L3,Offer3,Agent,1131.464935,Four-Door Car,Medsize
2,AI49188,Nevada,12887.431650,No,Premium,Bachelor,2/19/11,Employed,F,48767,...,38,0,2,Personal Auto,Personal L3,Offer1,Agent,566.472247,Two-Door Car,Medsize
3,WW63253,California,7645.861827,No,Basic,Bachelor,1/20/11,Unemployed,M,0,...,65,0,7,Corporate Auto,Corporate L2,Offer1,Call Center,529.881344,SUV,Medsize
4,HB64268,Washington,2813.692575,No,Basic,Bachelor,2/3/11,Employed,M,43836,...,44,0,1,Personal Auto,Personal L1,Offer1,Agent,138.130879,Four-Door Car,Medsize
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9129,LA72316,California,23405.987980,No,Basic,Bachelor,2/10/11,Employed,M,71941,...,89,0,2,Personal Auto,Personal L1,Offer2,Web,198.234764,Four-Door Car,Medsize
9130,PK87824,California,3096.511217,Yes,Extended,College,2/12/11,Employed,F,21604,...,28,0,1,Corporate Auto,Corporate L3,Offer1,Branch,379.200000,Four-Door Car,Medsize
9131,TD14365,California,8163.890428,No,Extended,Bachelor,2/6/11,Unemployed,M,0,...,37,3,2,Corporate Auto,Corporate L2,Offer1,Branch,790.784983,Four-Door Car,Medsize
9132,UP19263,California,7524.442436,No,Extended,College,2/3/11,Employed,M,21941,...,3,0,3,Personal Auto,Personal L2,Offer3,Branch,691.200000,Four-Door Car,Large
9133,Y167826,California,2611.836866,No,Extended,College,2/14/11,Unemployed,M,0,...,90,0,1,Corporate Auto,Corporate L3,Offer4,Call Center,369.600000,Two-Door Car,Medsize

In [3]:
X=data.drop("Total Claim Amount", axis=1)
y=data["Total Claim Amount"]

In [4]:
numerical_cols = X.select_dtypes(include=['float', 'int']).columns
X_num = X[numerical_cols]

In [5]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_num)
data[numerical_cols] = X_scaled

In [6]:
data

,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,Income,...,Months Since Policy Inception,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size
0,BU79786,Washington,-0.762878,No,Basic,Bachelor,2/24/11,Employed,F,0.612827,...,-1.543287,-0.422250,-0.822648,Corporate Auto,Corporate L3,Offer1,Agent,384.811147,Two-Door Car,Medsize
1,QZ44356,Arizona,-0.149245,No,Extended,Bachelor,1/31/11,Unemployed,F,-1.239617,...,-0.217334,-0.422250,2.106160,Personal Auto,Personal L3,Offer3,Agent,1131.464935,Four-Door Car,Medsize
2,AI49188,Nevada,0.710636,No,Premium,Bachelor,2/19/11,Employed,F,0.365710,...,-0.360680,-0.422250,-0.404247,Personal Auto,Personal L3,Offer1,Agent,566.472247,Two-Door Car,Medsize
3,WW63253,California,-0.052263,No,Basic,Bachelor,1/20/11,Unemployed,M,-1.239617,...,0.606907,-0.422250,1.687759,Corporate Auto,Corporate L2,Offer1,Call Center,529.881344,SUV,Medsize
4,HB64268,Washington,-0.755575,No,Basic,Bachelor,2/3/11,Employed,M,0.203390,...,-0.145661,-0.422250,-0.822648,Personal Auto,Personal L1,Offer1,Agent,138.130879,Four-Door Car,Medsize
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9129,LA72316,California,2.241590,No,Basic,Bachelor,2/10/11,Employed,M,1.128558,...,1.466984,-0.422250,-0.404247,Personal Auto,Personal L1,Offer2,Web,198.234764,Four-Door Car,Medsize
9130,PK87824,California,-0.714411,Yes,Extended,College,2/12/11,Employed,F,-0.528450,...,-0.719046,-0.422250,-0.822648,Corporate Auto,Corporate L3,Offer1,Branch,379.200000,Four-Door Car,Medsize
9131,TD14365,California,0.023135,No,Extended,Bachelor,2/6/11,Unemployed,M,-1.239617,...,-0.396517,2.873245,-0.404247,Corporate Auto,Corporate L2,Offer1,Branch,790.784983,Four-Door Car,Medsize
9132,UP19263,California,-0.069935,No,Extended,College,2/3/11,Employed,M,-0.517356,...,-1.614960,-0.422250,0.014154,Personal Auto,Personal L2,Offer3,Branch,691.200000,Four-Door Car,Large
9133,Y167826,California,-0.784955,No,Extended,College,2/14/11,Unemployed,M,-1.239617,...,1.502821,-0.422250,-0.822648,Corporate Auto,Corporate L3,Offer4,Call Center,369.600000,Two-Door Car,Medsize

In [7]:
categorical_cols = list(data.select_dtypes(include=["object"]).columns)

In [8]:
X_cat = data[categorical_cols]
encoder = LabelEncoder()
X_encoded = X_cat.apply(encoder.fit_transform)

In [9]:
data[categorical_cols] = X_encoded

In [18]:
y=data['Total Claim Amount']
X=data.drop("Total Claim Amount",axis=1)

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [23]:
lm=linear_model.LinearRegression().fit(X_train,y_train)

In [24]:
predictions=lm.predict(X_train)

In [33]:
r2=r2_score(y_train,predictions)
mean_squared=mean_squared_error(y_train,predictions)
root_mean_squared = np.sqrt(mean_squared)
mean_absolute=mean_absolute_error(y_train,predictions)

In [34]:
print(r2)
print(mean_squared)
print(root_mean_squared)
print(mean_absolute)

0.6103277323286401
33337.10337985019
182.58451024073807
131.77794803199328